spring:
  datasource:
    druid:
      #      url: jdbc:mysql://localhost:3306/imooc-bilibili?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      url: jdbc:mysql://192.168.206.201:3306/imooc-bilibili?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      # password: 1234

  redis:
    #    host: 127.0.0.1
    host: 192.168.206.201
    port: 6379
    password:

rocketmq:
  name:
    server:
      address: 192.168.206.201:9876
#      address: 127.0.0.1:9876
fdfs:
  tracker-list: 192.168.206.201:22122
  so-timeout: 1000
  connect-timeout: 601
  http:
    storage-addr: http://192.168.206.201:8888/group1/