spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/imooc-bilibili?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
  redis:
    host: 127.0.0.1
    port: 6379
    password:

rocketmq:
  name:
    server:
      address: 127.0.0.1:9876